language: go

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - GOARCH=amd64 GOOS=linux   go build -o art-linux
  - GOARCH=amd64 GOOS=darwin  go build -o art-darwin
  - GOARCH=amd64 GOOS=windows go build -o art-windows.exe

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: 
    - art-linux
    - art-darwin
    - art-windows.exe
  skip_cleanup: true
  on:
    tags: true
